version: '3.8'

services:
  app:
    image: sciohub/term-curation-ui:dev
    container_name: react-app
    restart: unless-stopped
    ports:
      - 3000:80
    networks:
      - default

networks:
  default:
    name: app